frontend/urls.py
import uuid
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'frontend'

urlpatterns = [
    re_path(r"^api/inst-data/entity-status(?:/(?P<entity_id>[0-9a-fA-F-]{36}))?/$", views.get_entity_status, name="get_entity_status"),
    path("api/inst-data/<str:metric>/", views.get_instantaneous_data, name="get_instantaneous_data"),
    path("api/range-data/<str:metric>/", views.get_range_data, name="get_range_data"),
    path('api/online-entities/', views.get_online_entities, name='get_online_entities'),

]

page_urlpatterns = [
    path('', views.index, name="index"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('resources/', views.resources, name="resources"),
    path('network/', views.network, name="network"),
    path('backup/', views.backup, name="backup"),
    # path('report/', views.report, name="report"),
    path('endpoints/', views.ListEndpointsView.as_view(), name='endpoints'),
]

endpoints_urlpattern = [
    path('endpoint/<uuid:endpoint_id>/change/', views.edit_endpoint, name="change_endpoint"),
    path('endpoint/add/', views.edit_endpoint, name="add_endpoint"),
    path('endpoints/<uuid:pk>/delete/', views.DeleteEndpointView.as_view(), name='delete_endpoint'),
]

urlpatterns += page_urlpatterns
urlpatterns += endpoints_urlpattern

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from backend.initcmds import init_db_query, init_server, init_backup, init_endpoint
from users.initcmds import init_db_users, init_db_groups

init_db_query()
init_db_users()
init_db_groups()
init_server()
init_backup()
init_endpoint()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
import uuid
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.UserCreateView.as_view(), name='register'),
    path("login/", auth_views.LoginView.as_view(
        template_name="users/base.html",
        extra_context={
            "page_title": "Login",
            "header_text": "Sign-in",
            "button_text": "Sign In",
            "extra_links": '<a href="/password-reset/">Forgot your password?</a> <br> <hr> <a href="/register/">Create a new account</a>'
        }
    ), name="login"),    
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit_profile/', views.UserUpdateView.as_view(), name='edit_profile'),

    path('password-reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete')  # ← qui la modifica
        ),
        name='password_reset_confirm'
    ),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),

    path('set-active-server/', views.set_active_server, name='set_active_server'),
    path('set-active-backup-server/', views.set_active_backup_server, name='set_active_backup_server'),
    path('set-active-endpoint/', views.set_active_endpoint, name='set_active_endpoint'),
    path('set-date-range/', views.set_date_range, name='set_date_range'),

]

frontend/forms.py
from django import forms 

from backend.models import Endpoint

class EndpointForm(forms.ModelForm):

    class Meta:
        model = Endpoint
        fields = [
            'name',
            'url',
            'description',
            'logo',
            # 'check_keyword',
            'user',
        ]
        widgets = {'user': forms.HiddenInput()}

frontend/views.py
import traceback
from datetime import datetime
from uuid import UUID

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import (
    HttpResponse, JsonResponse, HttpResponseBadRequest, HttpResponseForbidden, HttpResponseRedirect
)
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_GET, require_POST
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView

from backend.models import PromQuery, Endpoint, Server
from .forms import EndpointForm
from .decorators import require_pro_user
from main import api, settings
from django.template.loader import render_to_string


################### Main pages ###################

"""
Views used to implement two different entry point, one for PRO user and one for FREE user
"""
@login_required
@require_GET
def index(request):
    if request.user.is_pro:
        return HttpResponseRedirect('/dashboard/')
    return HttpResponseRedirect('/network/')


"""
The synoptic look on all the entity status; it's the entry point for PRO user
"""
@login_required
@require_GET
@require_pro_user
def dashboard(request):
    return render(request, 'frontend/pages/dashboard.html', {
    })

"""
This is the presentation of the metrics for a single SERVER at a time;
PRO user here can have a fine-grained look on their server status.
"""
@login_required
@require_GET
@require_pro_user
def resources(request):
    widgets = [
        {"title": "Operative System", "metric": "os", "url_name": "frontend:get_instantaneous_data", "icon": "bi-gear-fill"},
        {"title": "Server Status", "metric": "", "url_name": "frontend:get_entity_status", "icon": "bi-circle-half"},
        {"title": "Uptime since last boot", "metric": "uptime-days", "url_name": "frontend:get_instantaneous_data", "icon": "bi-clock-history", "unit": "days"},
        {"title": "Http request (5m)", "metric": "http-req", "url_name": "frontend:get_instantaneous_data", "icon": "bi-activity"},
        {"title": "CPU Usage", "metric": "cpu-usage", "url_name": "frontend:get_instantaneous_data", "icon": "bi-cpu", "unit": "%", "col": 3},
        # {"title": "Memory Used", "metric": "mem-used", "url_name": "frontend:get_instantaneous_data", "icon": "bi-memory", "unit": "GB","col": 3},
        # {"title": "Disk Used", "metric": "disk-used", "url_name": "frontend:get_instantaneous_data", "icon": "bi-hdd-fill", "unit": "GB","col": 3},
    ]
    charts = [
        {"id": "cpuChart", "title": "CPU Usage Trend", "metric": "cpu-usage:server:0", "color": "#0d6efd"},
        {"id": "memoryChart", "title": "Memory Usage Trend", "metric": "mem-used:server:0", "color": "#6610f2"},
        {"id": "diskChart", "title": "Disk Trend", "metric": "disk-used:server:0", "color": "#a110a2"},
        {"id": "requestChart", "title": "Http request Trend", "metric": "http-req:server:0", "color": "#c110a2"},
    ]
    return render(request, "frontend/pages/resources.html", {
        "widgets": widgets,
        "charts": charts,
    })


"""
This is the presentation of the metrics for a single ENDPOINT at a time;
all user here can have a fine-grained look on their endpoint status.
"""
@login_required
@require_GET
def network(request):
    widgets = [
        {"title": "Endpoint Status", "metric": "", "url_name": "frontend:get_entity_status", "icon": "bi-circle-half", "source": "endpoint"},
        {"title": "Latency", "metric": "response-time", "url_name": "frontend:get_instantaneous_data", "icon": "bi-activity", "source": "endpoint", "unit": "ms"},
        {"title": "Days until cert. expiration", "metric": "cert-days-rem", "url_name": "frontend:get_instantaneous_data", "icon": "bi-lock-fill", "source": "endpoint"},
        {"title": "Uptime (last 30d)", "metric": "uptime-perc", "url_name": "frontend:get_instantaneous_data", "icon": "bi-clock-history", "source": "endpoint", "unit": "%"},
    ]

    charts = [
        {"id": "latencyChart", "title": "Latency trend", "metric": "response-time:endpoint:0", "color": "#0d6efd", "col": 12},
        {"id": "uptimeChart", "title": "Uptime trend", "metric": "monitor-status:endpoint:0", "color": "#6610f2", "col": 12, "entity": "endpoint"},
    ]

    return render(request, "frontend/pages/info.html", {
        "widgets": widgets,
        "charts": charts,
    })

"""
This is the presentation of the metrics for a single backup-server at a time;
PRO user here can have a fine-grained look on their backup-server status.
"""
@login_required
@require_GET
@require_pro_user
def backup(request):
    widgets = [
        {"title": "Restic status", "metric": "", "url_name": "frontend:get_entity_status", "icon": "bi-circle-half", "source": "backup"},
        {"title": "Last snapshot", "metric": "last-snap-timestamp", "url_name": "frontend:get_instantaneous_data", "icon": "bi-clock-history", "source": "backup", "unit": "hours ago"},
        {"title": "Snapshots count", "metric": "snaps-count", "url_name": "frontend:get_instantaneous_data", "icon": "bi-123", "source": "backup"},
    ]
    charts = [
        {"id": "snapcountChart", "title": "Snapshot count Trend", "metric": "snaps-count:backup:0", "color": "#a110a2", "col": 12, "entity": "backup"},
        {"id": "filesizeChart", "title": "File size per snapshot Trend (GB)", "metric": "snap-size:backup:0", "color": "#6610f2", "col": 12, "entity": "backup"},
        {"id": "filecountChart", "title": "File count per snapshot trend", "metric": "snap-file-count:backup:0", "color": "#0d6efd", "col": 12, "entity": "backup"},
    ]
    return render(request, "frontend/pages/info.html", {
        "widgets": widgets,
        "charts": charts,
    })


@login_required
@require_GET
@require_pro_user
def report(request):
    return render(request, 'frontend/pages/report.html', {
    })

################### Dashboard ###################

def _get_up_down_count(query_code, str_entities, count):
    if not str_entities:
        return 0, 0
    try:
        prom_q = PromQuery.objects.get(code=query_code)
        up = int(api.generic_call(str_entities, prom_q, 0))
        down = count - up
        return up, down
    except Exception as e:
        return 0, count
    
@login_required
@require_GET
def get_online_entities(request):
    user = request.user

    servers = user.get_accessible_servers_string()
    servers_up, servers_down = _get_up_down_count("is-on-all", servers, len(user.get_accessible_servers()))

    endpoints = user.get_accessible_endpoints_string()
    endpoints_up, endpoints_down = _get_up_down_count("monitor-status-all", endpoints, len(user.get_accessible_endpoints()))
    
    backups = user.get_accessible_backup_servers_string()
    backups_up, backups_down = _get_up_down_count("restic-up-all", backups, len(user.get_accessible_backup_servers()))

    return JsonResponse({
        'entities': {
            'up': servers_up + endpoints_up + backups_up,
            'down': servers_down + endpoints_down + backups_down,
        },
        'servers': {
            'up': servers_up,
            'down': servers_down,
        },
        'endpoints': {
            'up': endpoints_up,
            'down': endpoints_down,
        },
        'backups': {
            'up': backups_up,
            'down': backups_down,
        },
    })


###################################################

@login_required
@require_GET
def get_entity_status(request, entity_id=None):
    html = '?'
    qtype = 0
    source = request.GET.get("source", "server")
    
    try:
        if source == "server":
            if entity_id:
                entity_id = UUID(entity_id)
                active_server = get_object_or_404(Server, id=entity_id)
                if active_server not in request.user.get_accessible_servers():
                    raise PermissionDenied()
            else:
                active_server = request.user.active_server

            parameter = f"{active_server.domain}:{active_server.port}"
            metric = 'is-on'

        elif source == "backup":
            if entity_id:
                entity_id = UUID(entity_id)
                active_server = get_object_or_404(Server, id=entity_id)
                if active_server not in request.user.get_accessible_backup_servers():
                    raise PermissionDenied()
            else:
                active_server = request.user.active_backup_server

            parameter = f"{active_server.domain}:{active_server.port}"
            metric = 'restic-up'

        elif source == "endpoint":
            if entity_id:
                entity_id = UUID(entity_id)
                active_endpoint = get_object_or_404(Endpoint, id=entity_id)
                if active_endpoint not in request.user.get_accessible_endpoints():
                    raise PermissionDenied()
            else:
                active_endpoint = request.user.active_endpoint

            parameter = active_endpoint.url
            metric = 'monitor-status'

        else:
            return HttpResponseBadRequest("Unknown source")

        prom_query = PromQuery.objects.get(code=metric)
        response = api.generic_call(parameter, prom_query, qtype)

        color = "green" if int(response) == 1 else "red"
        html = render_to_string("frontend/components/status_dot.html", {
            "color": color,
            "dim": "22px",
            "title": f"Status: {'online' if int(response) == 1 else 'offline'}"
        })

    except Exception as e:
        # messages.error(request, 'Error while retrieving entity status: ' + str(e))
        print("Error: " + str(e))
        tb_str = traceback.format_exc()
        print(tb_str)
        
    return HttpResponse(html)

######################################################

################### Endpoints ###################

frontend/templates/frontend/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %} {{SITE_TITLE}} {% endblock title %}</title>
        
        <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" rel="stylesheet">
        <link href="{% static 'dygraphs/dist/dygraph.css' %}" rel="stylesheet">
        <link rel='stylesheet' href="{% static 'htmx_forms.css' %}">

        <link href="{% static 'frontend/css/style.css' %}" rel="stylesheet">

        {% comment %} <meta name="csrf-token" content="{{ csrf_token }}"> {% endcomment %}

    </head>
    <body>

        <div class="d-flex">

            <!-- Sidebar -->
            {% block sidebar %}
                {% include "frontend/components/sidebar.html" %}
            {% endblock sidebar %}

            <div class="flex-grow-1" style="margin-left: 280px;">

                <div class="p-4">
                {% if messages %}
                <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
                </div>
                {% endif %}
                {% if user.is_authenticated %}
                    <div style="position: absolute; top: 10px; right: 20px; font-size: 0.9rem;">
                        <strong>Groups:</strong>
                        {% for group in user.groups.all %}
                            <span style="margin-right: 5px;">{{ group.name }}</span>
                        {% empty %}
                            <span>None</span>
                        {% endfor %}
                    </div>
                {% endif %}


                    {% block content %}
                        <h2>Content goes here</h2>
                    {% endblock content %}
                    
                </div>
            </div>
        </div>
        {% include 'htmx_forms/dialogs.html' %}
        {% include 'htmx_forms/overlay.html' %}

        <script src="{% static 'bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'htmx.org/dist/htmx.js' %}"></script>
        <script type="text/javascript" src="{% static 'dygraphs/dist/dygraph.js' %}"></script>
        <script src="{% static 'htmx_forms.js' %}"></script>

        {% block extrajs %}
        {% endblock extrajs %}
    </body>
</html>

frontend/templates/frontend/info_base.html
{% extends "frontend/base.html" %}
{% block content %}
    {% block entity_selector %}
        {% if request.resolver_match.url_name == "network" %}
            {% include "frontend/components/endpoint_select.html" %}
        {% elif request.resolver_match.url_name == "resources" %}
            {% include "frontend/components/server_select.html" %}
        {% elif request.resolver_match.url_name == "backup" %}
            {% include "frontend/components/backup_select.html" %}
        {% endif %}
    {% endblock entity_selector %}
    
    <h2 class="text-center"> Actual values </h2>
    {% block actual_values %}
    {% endblock actual_values %}
    <br>
    <hr>
    <br>

    {% block date_selector %}
        <div class="container mb-4">
    <h2 class="text-center">Historical values</h2>
    <form id="data-range-form" method="POST" action="{% url 'users:set_date_range' %}" class="row g-2 align-items-center justify-content-start">
        {% csrf_token %}
        <div class="col-auto">
        <label for="start-date" class="col-form-label small mb-0">From:</label>
        </div>
        <div class="col-auto">
        <input type="date" id="start-date" name="start_date" class="form-control form-control-sm"
                value="{{ request.user.get_active_date_filters.date_from|date:'Y-m-d' }}">
        </div>
        <div class="col-auto">
        <label for="end-date" class="col-form-label small mb-0">To:</label>
        </div>
        <div class="col-auto">
        <input type="date" id="end-date" name="end_date" class="form-control form-control-sm"
                value="{{ request.user.get_active_date_filters.date_to|date:'Y-m-d' }}">
        </div>
        <div class="col-auto">
        <button type="submit" class="btn btn-sm btn-primary">Apply</button>
        </div>
    </form>
    </div>
    {% endblock date_selector %}

    {% block charts %}
        <h3> Charts </h3>
    {% endblock charts %}
{% endblock content %}