frontend/urls.py
import uuid
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'frontend'

urlpatterns = [
    re_path(r"^api/inst-data/entity-status(?:/(?P<entity_id>[0-9a-fA-F-]{36}))?/$", views.get_entity_status, name="get_entity_status"),
    path("api/inst-data/<str:metric>/", views.get_instantaneous_data, name="get_instantaneous_data"),
    path("api/range-data/<str:metric>/", views.get_range_data, name="get_range_data"),
    path('api/online-entities/', views.get_online_entities, name='get_online_entities'),

]

page_urlpatterns = [
    path('', views.index, name="index"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('resources/', views.resources, name="resources"),
    path('network/', views.network, name="network"),
    path('backup/', views.backup, name="backup"),
    # path('report/', views.report, name="report"),
    path('endpoints/', views.ListEndpointsView.as_view(), name='endpoints'),
]

endpoints_urlpattern = [
    path('endpoint/<uuid:endpoint_id>/change/', views.edit_endpoint, name="change_endpoint"),
    path('endpoint/add/', views.edit_endpoint, name="add_endpoint"),
    path('endpoints/<uuid:pk>/delete/', views.DeleteEndpointView.as_view(), name='delete_endpoint'),
]

urlpatterns += page_urlpatterns
urlpatterns += endpoints_urlpattern

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from backend.initcmds import init_db_query, init_server, init_backup, init_endpoint
from users.initcmds import init_db_users, init_db_groups

init_db_query()
init_db_users()
init_db_groups()
init_server()
init_backup()
init_endpoint()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/forms.py
from django import forms 

from backend.models import Endpoint

class EndpointForm(forms.ModelForm):

    class Meta:
        model = Endpoint
        fields = [
            'name',
            'url',
            'description',
            'logo',
            # 'check_keyword',
            'user',
        ]
        widgets = {'user': forms.HiddenInput()}

frontend/views.py
import traceback
from datetime import datetime
from uuid import UUID

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import (
    HttpResponse, JsonResponse, HttpResponseBadRequest, HttpResponseForbidden, HttpResponseRedirect
)
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_GET, require_POST
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView

from backend.models import PromQuery, Endpoint, Server
from .forms import EndpointForm
from .decorators import require_pro_user
from main import api, settings
from django.template.loader import render_to_string


################### Main pages ###################

"""
Views used to implement two different entry point, one for PRO user and one for FREE user
"""
@login_required
@require_GET
def index(request):
    if request.user.is_pro:
        return HttpResponseRedirect('/dashboard/')
    return HttpResponseRedirect('/network/')


"""
The synoptic look on all the entity status; it's the entry point for PRO user
"""
@login_required
@require_GET
@require_pro_user
def dashboard(request):
    return render(request, 'frontend/pages/dashboard.html', {
    })

"""
This is the presentation of the metrics for a single SERVER at a time;
PRO user here can have a fine-grained look on their server status.
"""
@login_required
@require_GET
@require_pro_user
def resources(request):
    widgets = [
        {"title": "Operative System", "metric": "os", "url_name": "frontend:get_instantaneous_data", "icon": "bi-gear-fill"},
        {"title": "Server Status", "metric": "", "url_name": "frontend:get_entity_status", "icon": "bi-circle-half"},
        {"title": "Uptime since last boot", "metric": "uptime-days", "url_name": "frontend:get_instantaneous_data", "icon": "bi-clock-history", "unit": "days"},
        {"title": "Http request (5m)", "metric": "http-req", "url_name": "frontend:get_instantaneous_data", "icon": "bi-activity"},
        {"title": "CPU Usage", "metric": "cpu-usage", "url_name": "frontend:get_instantaneous_data", "icon": "bi-cpu", "unit": "%", "col": 3},
        # {"title": "Memory Used", "metric": "mem-used", "url_name": "frontend:get_instantaneous_data", "icon": "bi-memory", "unit": "GB","col": 3},
        # {"title": "Disk Used", "metric": "disk-used", "url_name": "frontend:get_instantaneous_data", "icon": "bi-hdd-fill", "unit": "GB","col": 3},
    ]
    charts = [
        {"id": "cpuChart", "title": "CPU Usage Trend", "metric": "cpu-usage:server:0", "color": "#0d6efd"},
        {"id": "memoryChart", "title": "Memory Usage Trend", "metric": "mem-used:server:0", "color": "#6610f2"},
        {"id": "diskChart", "title": "Disk Trend", "metric": "disk-used:server:0", "color": "#a110a2"},
        {"id": "requestChart", "title": "Http request Trend", "metric": "http-req:server:0", "color": "#c110a2"},
    ]
    return render(request, "frontend/pages/resources.html", {
        "widgets": widgets,
        "charts": charts,
    })


"""
This is the presentation of the metrics for a single ENDPOINT at a time;
all user here can have a fine-grained look on their endpoint status.
"""
@login_required
@require_GET
def network(request):
    widgets = [
        {"title": "Endpoint Status", "metric": "", "url_name": "frontend:get_entity_status", "icon": "bi-circle-half", "source": "endpoint"},
        {"title": "Latency", "metric": "response-time", "url_name": "frontend:get_instantaneous_data", "icon": "bi-activity", "source": "endpoint", "unit": "ms"},
        {"title": "Days until cert. expiration", "metric": "cert-days-rem", "url_name": "frontend:get_instantaneous_data", "icon": "bi-lock-fill", "source": "endpoint"},
        {"title": "Uptime (last 30d)", "metric": "uptime-perc", "url_name": "frontend:get_instantaneous_data", "icon": "bi-clock-history", "source": "endpoint", "unit": "%"},
    ]

    charts = [
        {"id": "latencyChart", "title": "Latency trend", "metric": "response-time:endpoint:0", "color": "#0d6efd", "col": 12},
        {"id": "uptimeChart", "title": "Uptime trend", "metric": "monitor-status:endpoint:0", "color": "#6610f2", "col": 12, "entity": "endpoint"},
    ]

    return render(request, "frontend/pages/info.html", {
        "widgets": widgets,
        "charts": charts,
    })

"""
This is the presentation of the metrics for a single backup-server at a time;
PRO user here can have a fine-grained look on their backup-server status.
"""
@login_required
@require_GET
@require_pro_user
def backup(request):
    widgets = [
        {"title": "Restic status", "metric": "", "url_name": "frontend:get_entity_status", "icon": "bi-circle-half", "source": "backup"},
        {"title": "Last snapshot", "metric": "last-snap-timestamp", "url_name": "frontend:get_instantaneous_data", "icon": "bi-clock-history", "source": "backup", "unit": "hours ago"},
        {"title": "Snapshots count", "metric": "snaps-count", "url_name": "frontend:get_instantaneous_data", "icon": "bi-123", "source": "backup"},
    ]
    charts = [
        {"id": "snapcountChart", "title": "Snapshot count Trend", "metric": "snaps-count:backup:0", "color": "#a110a2", "col": 12, "entity": "backup"},
        {"id": "filesizeChart", "title": "File size per snapshot Trend (GB)", "metric": "snap-size:backup:0", "color": "#6610f2", "col": 12, "entity": "backup"},
        {"id": "filecountChart", "title": "File count per snapshot trend", "metric": "snap-file-count:backup:0", "color": "#0d6efd", "col": 12, "entity": "backup"},
    ]
    return render(request, "frontend/pages/info.html", {
        "widgets": widgets,
        "charts": charts,
    })


@login_required
@require_GET
@require_pro_user
def report(request):
    return render(request, 'frontend/pages/report.html', {
    })

################### Dashboard ###################

def _get_up_down_count(query_code, str_entities, count):
    if not str_entities:
        return 0, 0
    try:
        prom_q = PromQuery.objects.get(code=query_code)
        up = int(api.generic_call(str_entities, prom_q, 0))
        down = count - up
        return up, down
    except Exception as e:
        return 0, count
    
@login_required
@require_GET
def get_online_entities(request):
    user = request.user

    servers = user.get_accessible_servers_string()
    servers_up, servers_down = _get_up_down_count("is-on-all", servers, len(user.get_accessible_servers()))

    endpoints = user.get_accessible_endpoints_string()
    endpoints_up, endpoints_down = _get_up_down_count("monitor-status-all", endpoints, len(user.get_accessible_endpoints()))
    
    backups = user.get_accessible_backup_servers_string()
    backups_up, backups_down = _get_up_down_count("restic-up-all", backups, len(user.get_accessible_backup_servers()))

    return JsonResponse({
        'entities': {
            'up': servers_up + endpoints_up + backups_up,
            'down': servers_down + endpoints_down + backups_down,
        },
        'servers': {
            'up': servers_up,
            'down': servers_down,
        },
        'endpoints': {
            'up': endpoints_up,
            'down': endpoints_down,
        },
        'backups': {
            'up': backups_up,
            'down': backups_down,
        },
    })


###################################################

@login_required
@require_GET
def get_entity_status(request, entity_id=None):
    html = '?'
    qtype = 0
    source = request.GET.get("source", "server")
    
    try:
        if source == "server":
            if entity_id:
                entity_id = UUID(entity_id)
                active_server = get_object_or_404(Server, id=entity_id)
                if active_server not in request.user.get_accessible_servers():
                    raise PermissionDenied()
            else:
                active_server = request.user.active_server

            parameter = f"{active_server.domain}:{active_server.port}"
            metric = 'is-on'

        elif source == "backup":
            if entity_id:
                entity_id = UUID(entity_id)
                active_server = get_object_or_404(Server, id=entity_id)
                if active_server not in request.user.get_accessible_backup_servers():
                    raise PermissionDenied()
            else:
                active_server = request.user.active_backup_server

            parameter = f"{active_server.domain}:{active_server.port}"
            metric = 'restic-up'

        elif source == "endpoint":
            if entity_id:
                entity_id = UUID(entity_id)
                active_endpoint = get_object_or_404(Endpoint, id=entity_id)
                if active_endpoint not in request.user.get_accessible_endpoints():
                    raise PermissionDenied()
            else:
                active_endpoint = request.user.active_endpoint

            parameter = active_endpoint.url
            metric = 'monitor-status'

        else:
            return HttpResponseBadRequest("Unknown source")

        prom_query = PromQuery.objects.get(code=metric)
        response = api.generic_call(parameter, prom_query, qtype)

        color = "green" if int(response) == 1 else "red"
        html = render_to_string("frontend/components/status_dot.html", {
            "color": color,
            "dim": "22px",
            "title": f"Status: {'online' if int(response) == 1 else 'offline'}"
        })

    except Exception as e:
        # messages.error(request, 'Error while retrieving entity status: ' + str(e))
        print("Error: " + str(e))
        tb_str = traceback.format_exc()
        print(tb_str)
        
    return HttpResponse(html)

######################################################

################### Endpoints ###################

frontend/templates/frontend/pages/dashboard.html
{% extends "frontend/info_base.html" %}
{% load static %}

{% block actual_values %}
<div class="container">
  <div class="row justify-content-center align-items-stretch">
    <!-- Colonna 1 -->
    <div class="col-md-2">
      <div class="p-3 text-center">
        <h5>Entities online</h5>
        <div id="gaugeEntities"></div>
        <div id="textEntities" class="mt-2 fw-bold text-success"></div>
      </div>
    </div>

    <!-- Separatore verticale -->
    <div class="col-md-1 d-flex justify-content-center">
      <div style="width: 1px; background-color: #ccc; height: 100%;"></div>
    </div>

    <!-- Colonna 2 -->
    <div class="col-md-2">
      <div class="p-3 text-center">
        <h6>Servers</h6>
        <div id="gaugeServers"></div>
        <div id="textServers" class="mt-2 fw-bold text-success"></div>
      </div>
    </div>

    <!-- Colonna 3 -->
    <div class="col-md-2">
      <div class="p-3 text-center">
        <h6>Endpoints</h6>
        <div id="gaugeEndpoints"></div>
        <div id="textEndpoints" class="mt-2 fw-bold text-success"></div>
      </div>
    </div>

        <!-- Colonna 4 -->
    <div class="col-md-2">
      <div class="p-3 text-center">
        <h6>Backup Servers</h6>
        <div id="gaugeBackups"></div>
        <div id="textBackups" class="mt-2 fw-bold text-success"></div>
      </div>
    </div>
    
  </div>
</div>
{% endblock %}

{% block charts %}
<br>

<div class="row mt-3">
  <div class="col-md-12">
    <div class="chart-card p-3 bg-white border rounded shadow-sm">
      <div class="d-flex justify-content-between align-items-center mb-2">
        <h6 class="text-muted mb-0">Uptime trend</h6>
      </div>
      <div class="chart"
           id="uptimeChart"
           data-metric="monitor-status-all:endpoint:all;is-on-all:server:all;restic-up-all:backup:all;">
      </div>
    </div>
  </div>
</div>


{% comment %} <div class="row mt-3">
  <div class="col-md-12">
    <div class="chart-card p-3 bg-white border rounded shadow-sm">
      <div class="d-flex justify-content-between align-items-center mb-2">
        <h6 class="text-muted mb-0">CPU trend</h6>
      </div>
      <div class="chart"
           id="resourcesChart"
           data-metric="cpu-usage:server:all"
           data-color="#0d6efd;#a110a2;#6610f2">
      </div>
    </div>
  </div>
</div> {% endcomment %}

{% endblock charts %}

{% block extrajs %}
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src="{% static "frontend/js/graphs.js" %}"></script>
<script src="{% static "frontend/js/dashboard.js" %}"></script>
{% endblock extrajs %}

frontend/templates/frontend/pages/endpoints.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}

<h2></h2>

<nav class="navbar navbar-light bg-light" style="justify-content: right; align-items: right;">
    {% if can_add_endpoint %}
    <a href="{% url 'frontend:add_endpoint' %}" onclick="onOpenDialog(event, 'Save')" data-title="Add an Endpoint" class="btn btn-success">
        Add
    </a>
    {% else %}
    <button class="btn btn-success" disabled title="Upgrade to PRO in order to add more Endpoints.">
        Add
    </button>
    {% endif %}
</nav>

<br>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Name</th>
            {% comment %} <th scope="col">Description</th> {% endcomment %}
            <th scope="col">URL</th>
            <th scope="col">Group</th>
            <th scope="col">Endpoint status</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for p in endpoint_list %}
        <tr>
            <td>
                {% if p.logo %}
                <img src="{{ p.logo.url }}" alt="Logo server" width="36" height="36" class="rounded-circle me-2">
                {% endif %}
            </td>
            <td>
                <a href="{% url 'frontend:change_endpoint' p.id %}" onclick="onOpenDialog(event, 'Save')" data-title="Edit an Endpoint">
                    {{ p.name }}
                </a>
            </td>
            {% comment %} <td>{{ p.description }}</td> {% endcomment %}
            <td>{{ p.url }}</td>
            <td>{{ p.group }} </td>
            <td hx-get="{% url 'frontend:get_entity_status' p.id %}?source=endpoint"  hx-trigger="load, every 60s" hx-target="this" hx-swap="innerHTML">
                Loading...
            </td>

            <td class="pe-4" style="width: 1%; white-space: nowrap;">
                <a href="{% url 'frontend:delete_endpoint' p.id %}" onclick="onOpenDialog(event, 'Delete')" data-title="Delete an Endpoint" class="btn btn-danger">
                    Delete
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

{% block extrajs %}
<script src="{% static "frontend/js/endpoint_dialogs.js" %}"></script>
{% endblock extrajs %}

frontend/templates/frontend/pages/info.html
{% extends "frontend/info_base.html" %}
{% block actual_values %}


<div class="container mt-4">
  <div class="row text-center g-3">

    <div class="row g-3 justify-content-center text-center">

      {% comment %} Beginning of the top line with the actual/instanteneous values {% endcomment %}
      {% for w in widgets %}
        {% comment %} We create a column for every widget {% endcomment %}
      <div class="col-md-{{ w.col|default:2 }}">
        <div class="p-3 bg-light border rounded shadow-sm h-100">
          <div class="text-muted small mb-1">
            <i class="bi {{ w.icon }}"></i> {{ w.title }}
          </div>
          <div class="fs-4 fw-bold text-dark">

            {% comment %} The url is generated dinamically, depending on the metric or not {% endcomment %}
            {% if w.metric %}
              {% url w.url_name metric=w.metric as widget_url %}
            {% else %}
              {% url w.url_name as widget_url %}
            {% endif %}

            {% comment %} Construction of the hx element for retrieve the data {% endcomment %}
            {% if w.source %} {% comment %} This is used only for endpoint {% endcomment %}
              {% with widget_url|add:"?source="|add:w.source as final_url %}
                <span 
                  hx-get="{{ final_url }}" 
                  hx-trigger="{{ w.trigger|default:'load' }}" 
                  hx-swap="outerHTML"
                  class="d-inline-block">
                  ?
                </span>
              {% endwith %}
            {% else %}
              <span 
                hx-get="{{ widget_url }}" 
                hx-trigger="{{ w.trigger|default:'load' }}" 
                hx-swap="outerHTML"
                class="d-inline-block">
                ?
              </span>
            {% endif %}

            {% if w.unit %}
              <small class="text-muted">{{ w.unit }}</small>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}

      {% block other_widgets %}
      
      {% endblock other_widgets %}

    </div>
  </div>
</div>

{% endblock actual_values %}

<hr class="mt-4 mb-3">


{% block charts %}
<div id="graphs-container">
  {% include "frontend/components/graphs.html" %}
</div>
{% endblock charts %}

frontend/templates/frontend/pages/report.html
{% extends "frontend/base.html" %}
{% block content %}

  <h2> Create your report </h2>

{% endblock content %}

frontend/templates/frontend/pages/resources.html
{% extends "frontend/pages/info.html" %}

{% block other_widgets %}
<!-- Memory Used -->
  <div class="col-md-3">
    <div class="p-3 bg-light border rounded shadow-sm h-100">
      <div class="text-muted small"><i class="bi bi-memory"></i> Memory Used</div>
      <div class="fs-5 fw-bold text-dark">
        <span 
          hx-get="{% url 'frontend:get_instantaneous_data' metric='mem-used' %}" 
          hx-trigger="load" 
          hx-swap="outerHTML">?
        </span> /
        <span 
          hx-get="{% url 'frontend:get_instantaneous_data' metric='mem-tot' %}" 
          hx-trigger="load" 
          hx-swap="outerHTML">?
        </span> GB
      </div>
      <div class="text-success small mt-1">
        Free: 
        <span 
          hx-get="{% url 'frontend:get_instantaneous_data' metric='mem-free' %}" 
          hx-trigger="load" 
          hx-swap="outerHTML">?
        </span> GB
      </div>
    </div>
  </div>

  <!-- Disk Used -->
  <div class="col-md-3">
    <div class="p-3 bg-light border rounded shadow-sm h-100">
      <div class="text-muted small"><i class="bi bi-hdd-fill"></i> Disk Used</div>
      <div class="fs-5 fw-bold text-dark">
        <span 
          hx-get="{% url 'frontend:get_instantaneous_data' metric='disk-used' %}" 
          hx-trigger="load" 
          hx-swap="outerHTML">?
        </span> /
        <span 
          hx-get="{% url 'frontend:get_instantaneous_data' metric='disk-tot' %}" 
          hx-trigger="load" 
          hx-swap="outerHTML">?
        </span> GB
      </div>
      <div class="text-success small mt-1">
        Free: 
        <span 
          hx-get="{% url 'frontend:get_instantaneous_data' metric='disk-free' %}" 
          hx-trigger="load" 
          hx-swap="outerHTML">?
        </span> GB
      </div>
    </div>
  </div>
{% endblock other_widgets %}