frontend/urls.py
import uuid
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'frontend'

urlpatterns = [
    re_path(r"^api/inst-data/entity-status(?:/(?P<entity_id>[0-9a-fA-F-]{36}))?/$", views.get_entity_status, name="get_entity_status"),
    path("api/inst-data/<str:metric>/", views.get_instantaneous_data, name="get_instantaneous_data"),
    path("api/range-data/<str:metric>/", views.get_range_data, name="get_range_data"),
    path('api/online-entities/', views.get_online_entities, name='get_online_entities'),

]

page_urlpatterns = [
    path('', views.index, name="index"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('resources/', views.resources, name="resources"),
    path('network/', views.network, name="network"),
    path('backup/', views.backup, name="backup"),
    # path('report/', views.report, name="report"),
    path('endpoints/', views.ListEndpointsView.as_view(), name='endpoints'),
]

endpoints_urlpattern = [
    path('endpoint/<uuid:endpoint_id>/change/', views.edit_endpoint, name="change_endpoint"),
    path('endpoint/add/', views.edit_endpoint, name="add_endpoint"),
    path('endpoints/<uuid:pk>/delete/', views.DeleteEndpointView.as_view(), name='delete_endpoint'),
]

urlpatterns += page_urlpatterns
urlpatterns += endpoints_urlpattern

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from backend.initcmds import init_db_query, init_server, init_backup, init_endpoint
from users.initcmds import init_db_users, init_db_groups

init_db_query()
init_db_users()
init_db_groups()
init_server()
init_backup()
init_endpoint()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
import uuid
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.UserCreateView.as_view(), name='register'),
    path("login/", auth_views.LoginView.as_view(
        template_name="users/base.html",
        extra_context={
            "page_title": "Login",
            "header_text": "Sign-in",
            "button_text": "Sign In",
            "extra_links": '<a href="/password-reset/">Forgot your password?</a> <br> <hr> <a href="/register/">Create a new account</a>'
        }
    ), name="login"),    
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit_profile/', views.UserUpdateView.as_view(), name='edit_profile'),

    path('password-reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete')  # ← qui la modifica
        ),
        name='password_reset_confirm'
    ),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),

    path('set-active-server/', views.set_active_server, name='set_active_server'),
    path('set-active-backup-server/', views.set_active_backup_server, name='set_active_backup_server'),
    path('set-active-endpoint/', views.set_active_endpoint, name='set_active_endpoint'),
    path('set-date-range/', views.set_date_range, name='set_date_range'),

]

frontend/forms.py
from django import forms 

from backend.models import Endpoint

class EndpointForm(forms.ModelForm):

    class Meta:
        model = Endpoint
        fields = [
            'name',
            'url',
            'description',
            'logo',
            # 'check_keyword',
            'user',
        ]
        widgets = {'user': forms.HiddenInput()}

frontend/views.py
import traceback
from datetime import datetime
from uuid import UUID

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import (
    HttpResponse, JsonResponse, HttpResponseBadRequest, HttpResponseForbidden, HttpResponseRedirect
)
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_GET, require_POST
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView

from backend.models import PromQuery, Endpoint, Server
from .forms import EndpointForm
from .decorators import require_pro_user
from main import api, settings
from django.template.loader import render_to_string


################### Main pages ###################

"""
Views used to implement two different entry point, one for PRO user and one for FREE user
"""
@login_required
@require_GET
def index(request):
    if request.user.is_pro:
        return HttpResponseRedirect('/dashboard/')
    return HttpResponseRedirect('/network/')


"""
The synoptic look on all the entity status; it's the entry point for PRO user
"""
@login_required
@require_GET
@require_pro_user
def dashboard(request):
    return render(request, 'frontend/pages/dashboard.html', {
    })

"""
This is the presentation of the metrics for a single SERVER at a time;
PRO user here can have a fine-grained look on their server status.
"""
@login_required
@require_GET
@require_pro_user
def resources(request):
    widgets = [
        {"title": "Operative System", "metric": "os", "url_name": "frontend:get_instantaneous_data", "icon": "bi-gear-fill"},
        {"title": "Server Status", "metric": "", "url_name": "frontend:get_entity_status", "icon": "bi-circle-half"},
        {"title": "Uptime since last boot", "metric": "uptime-days", "url_name": "frontend:get_instantaneous_data", "icon": "bi-clock-history", "unit": "days"},
        {"title": "Http request (5m)", "metric": "http-req", "url_name": "frontend:get_instantaneous_data", "icon": "bi-activity"},
        {"title": "CPU Usage", "metric": "cpu-usage", "url_name": "frontend:get_instantaneous_data", "icon": "bi-cpu", "unit": "%", "col": 3},
        # {"title": "Memory Used", "metric": "mem-used", "url_name": "frontend:get_instantaneous_data", "icon": "bi-memory", "unit": "GB","col": 3},
        # {"title": "Disk Used", "metric": "disk-used", "url_name": "frontend:get_instantaneous_data", "icon": "bi-hdd-fill", "unit": "GB","col": 3},
    ]
    charts = [
        {"id": "cpuChart", "title": "CPU Usage Trend", "metric": "cpu-usage:server:0", "color": "#0d6efd"},
        {"id": "memoryChart", "title": "Memory Usage Trend", "metric": "mem-used:server:0", "color": "#6610f2"},
        {"id": "diskChart", "title": "Disk Trend", "metric": "disk-used:server:0", "color": "#a110a2"},
        {"id": "requestChart", "title": "Http request Trend", "metric": "http-req:server:0", "color": "#c110a2"},
    ]
    return render(request, "frontend/pages/resources.html", {
        "widgets": widgets,
        "charts": charts,
    })


"""
This is the presentation of the metrics for a single ENDPOINT at a time;
all user here can have a fine-grained look on their endpoint status.
"""
@login_required
@require_GET
def network(request):
    widgets = [
        {"title": "Endpoint Status", "metric": "", "url_name": "frontend:get_entity_status", "icon": "bi-circle-half", "source": "endpoint"},
        {"title": "Latency", "metric": "response-time", "url_name": "frontend:get_instantaneous_data", "icon": "bi-activity", "source": "endpoint", "unit": "ms"},
        {"title": "Days until cert. expiration", "metric": "cert-days-rem", "url_name": "frontend:get_instantaneous_data", "icon": "bi-lock-fill", "source": "endpoint"},
        {"title": "Uptime (last 30d)", "metric": "uptime-perc", "url_name": "frontend:get_instantaneous_data", "icon": "bi-clock-history", "source": "endpoint", "unit": "%"},
    ]

    charts = [
        {"id": "latencyChart", "title": "Latency trend", "metric": "response-time:endpoint:0", "color": "#0d6efd", "col": 12},
        {"id": "uptimeChart", "title": "Uptime trend", "metric": "monitor-status:endpoint:0", "color": "#6610f2", "col": 12, "entity": "endpoint"},
    ]

    return render(request, "frontend/pages/info.html", {
        "widgets": widgets,
        "charts": charts,
    })

"""
This is the presentation of the metrics for a single backup-server at a time;
PRO user here can have a fine-grained look on their backup-server status.
"""
@login_required
@require_GET
@require_pro_user
def backup(request):
    widgets = [
        {"title": "Restic status", "metric": "", "url_name": "frontend:get_entity_status", "icon": "bi-circle-half", "source": "backup"},
        {"title": "Last snapshot", "metric": "last-snap-timestamp", "url_name": "frontend:get_instantaneous_data", "icon": "bi-clock-history", "source": "backup", "unit": "hours ago"},
        {"title": "Snapshots count", "metric": "snaps-count", "url_name": "frontend:get_instantaneous_data", "icon": "bi-123", "source": "backup"},
    ]
    charts = [
        {"id": "snapcountChart", "title": "Snapshot count Trend", "metric": "snaps-count:backup:0", "color": "#a110a2", "col": 12, "entity": "backup"},
        {"id": "filesizeChart", "title": "File size per snapshot Trend (GB)", "metric": "snap-size:backup:0", "color": "#6610f2", "col": 12, "entity": "backup"},
        {"id": "filecountChart", "title": "File count per snapshot trend", "metric": "snap-file-count:backup:0", "color": "#0d6efd", "col": 12, "entity": "backup"},
    ]
    return render(request, "frontend/pages/info.html", {
        "widgets": widgets,
        "charts": charts,
    })


@login_required
@require_GET
@require_pro_user
def report(request):
    return render(request, 'frontend/pages/report.html', {
    })

################### Dashboard ###################

def _get_up_down_count(query_code, str_entities, count):
    if not str_entities:
        return 0, 0
    try:
        prom_q = PromQuery.objects.get(code=query_code)
        up = int(api.generic_call(str_entities, prom_q, 0))
        down = count - up
        return up, down
    except Exception as e:
        return 0, count
    
@login_required
@require_GET
def get_online_entities(request):
    user = request.user

    servers = user.get_accessible_servers_string()
    servers_up, servers_down = _get_up_down_count("is-on-all", servers, len(user.get_accessible_servers()))

    endpoints = user.get_accessible_endpoints_string()
    endpoints_up, endpoints_down = _get_up_down_count("monitor-status-all", endpoints, len(user.get_accessible_endpoints()))
    
    backups = user.get_accessible_backup_servers_string()
    backups_up, backups_down = _get_up_down_count("restic-up-all", backups, len(user.get_accessible_backup_servers()))

    return JsonResponse({
        'entities': {
            'up': servers_up + endpoints_up + backups_up,
            'down': servers_down + endpoints_down + backups_down,
        },
        'servers': {
            'up': servers_up,
            'down': servers_down,
        },
        'endpoints': {
            'up': endpoints_up,
            'down': endpoints_down,
        },
        'backups': {
            'up': backups_up,
            'down': backups_down,
        },
    })


###################################################

@login_required
@require_GET
def get_entity_status(request, entity_id=None):
    html = '?'
    qtype = 0
    source = request.GET.get("source", "server")
    
    try:
        if source == "server":
            if entity_id:
                entity_id = UUID(entity_id)
                active_server = get_object_or_404(Server, id=entity_id)
                if active_server not in request.user.get_accessible_servers():
                    raise PermissionDenied()
            else:
                active_server = request.user.active_server

            parameter = f"{active_server.domain}:{active_server.port}"
            metric = 'is-on'

        elif source == "backup":
            if entity_id:
                entity_id = UUID(entity_id)
                active_server = get_object_or_404(Server, id=entity_id)
                if active_server not in request.user.get_accessible_backup_servers():
                    raise PermissionDenied()
            else:
                active_server = request.user.active_backup_server

            parameter = f"{active_server.domain}:{active_server.port}"
            metric = 'restic-up'

        elif source == "endpoint":
            if entity_id:
                entity_id = UUID(entity_id)
                active_endpoint = get_object_or_404(Endpoint, id=entity_id)
                if active_endpoint not in request.user.get_accessible_endpoints():
                    raise PermissionDenied()
            else:
                active_endpoint = request.user.active_endpoint

            parameter = active_endpoint.url
            metric = 'monitor-status'

        else:
            return HttpResponseBadRequest("Unknown source")

        prom_query = PromQuery.objects.get(code=metric)
        response = api.generic_call(parameter, prom_query, qtype)

        color = "green" if int(response) == 1 else "red"
        html = render_to_string("frontend/components/status_dot.html", {
            "color": color,
            "dim": "22px",
            "title": f"Status: {'online' if int(response) == 1 else 'offline'}"
        })

    except Exception as e:
        # messages.error(request, 'Error while retrieving entity status: ' + str(e))
        print("Error: " + str(e))
        tb_str = traceback.format_exc()
        print(tb_str)
        
    return HttpResponse(html)

######################################################

################### Endpoints ###################

frontend/templates/frontend/components/backup_select.html
<!-- Selezione endpoint -->
<form method="post" action="{% url 'users:set_active_backup_server' %}" class="d-flex align-items-center ms-2" style="white-space: nowrap;">
    {% csrf_token %}
    <label for="active-backup-select" class="me-2 mb-0 small">Select active backup server:</label>
    <select id="active-backup-select" name="backup_id"
            class="form-select form-select-sm py-0 px-1"
            style="height: 30px; font-size: 0.8rem; width: 300px;"
            >
            <option value="">... select a Backup Server... </option> 
      {% for backup_server in user.get_accessible_backup_servers %}
        <option value="{{ backup_server.id }}" {% if backup_server.id == user.active_backup_server.id %}selected{% endif %}>
          {{ backup_server }}
        </option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-sm btn-primary ms-2">Confirm</button>
  
  </form>
  

frontend/templates/frontend/components/delete_endpoint_confirmation.html
<h5 class="modal-title">Confirm deletion</h5>
    <form method="POST" action="{% url 'frontend:delete_endpoint' object.id %}">{% csrf_token %}
<div class="modal-body">
    Are you sure you want to delete <strong>{{ object.name }}</strong>?
</div>
</form>

frontend/templates/frontend/components/endpoint_form.html
{% load crispy_forms_tags %}

<form method="POST" action="{{action}}" class="form-container" novalidate>
    {% if form.non_field_errors %}
        <div class="alert alert-danger">
            {{ form.non_field_errors }}
        </div>
    {% endif %}
    {% csrf_token %}
    {{ form|crispy }}
</form>

frontend/templates/frontend/components/endpoint_select.html
<!-- Selezione endpoint -->
<form method="post" action="{% url 'users:set_active_endpoint' %}" class="d-flex align-items-center ms-2" style="white-space: nowrap;">
    {% csrf_token %}
    <label for="active-endpoint-select" class="me-2 mb-0 small">Select active endpoint:</label>
    <select id="active-endpoint-select" name="endpoint_id"
            class="form-select form-select-sm py-0 px-1"
            style="height: 30px; font-size: 0.8rem; width: 300px;"
            >
            <option value="">...  select an Endpoint...</option> 
      {% for endpoint in user.get_accessible_endpoints %}
        <option value="{{ endpoint.id }}" {% if endpoint.id == user.active_endpoint.id %}selected{% endif %}>
          {{ endpoint }}
        </option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-sm btn-primary ms-2">Confirm</button>
  
  </form>
  

frontend/templates/frontend/components/graphs.html
{% load static %}

<div class="row g-4">
  {% for chart in charts %}
  <div class="col-md-{{ chart.col|default:"6" }}">
    <div id="chart-card" class="p-3 bg-white border rounded shadow-sm">
      <h6 class="text-muted">{{ chart.title }}</h6>
      <div class="chart"
           id="{{ chart.id }}"
           data-metric="{{ chart.metric }}"
           {% if chart.entity %}data-entity="{{ chart.entity }}"{% endif %}
           data-color="{{ chart.color }}">
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% block extrajs %}
<script src="{% static "frontend/js/graphs.js" %}"></script>
{% endblock extrajs %}

frontend/templates/frontend/components/server_select.html
<!-- Selezione server -->
<form method="post" action="{% url 'users:set_active_server' %}" class="d-flex align-items-center ms-2" style="white-space: nowrap;">
    {% csrf_token %}
    <label for="active-server-select" class="me-2 mb-0 small">Select active server:</label>
    <select id="active-server-select" name="server_id"
            class="form-select form-select-sm py-0 px-1"
            style="height: 30px; font-size: 0.8rem; width: 300px;"
            >
            <option value="">... select a Server...</option> 
      {% for server in user.get_accessible_servers %}
        <option value="{{ server.id }}" {% if server.id == user.active_server.id %}selected{% endif %}>
          {{ server }}
        </option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-sm btn-primary ms-2">Confirm</button>
  
  </form>
  

frontend/templates/frontend/components/sidebar.html
{% load static %}
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark sidebar">
    <a href="{% if IS_USER_PRO %}/{% else %}/network{% endif %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <img src="{% static 'frontend/images/observa_logo_white.png' %}" alt="Default" width="40" height="40" class="rounded-circle me-2">
        <span class="fs-4">{{SITE_TITLE}}</span>
    </a>
<hr id="horizontalLine">


 <ul class="nav nav-pills flex-column mb-auto">
    <li>
        {% if IS_USER_PRO %}
        <a href="{% url 'frontend:dashboard' %}" class="nav-link text-white {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}">
        {% else %}
        <a class="nav-link text-secondary disabled" style="pointer-events: none; opacity: 0.5;"> <i class="bi bi-lock" style="margin-right: 6px;"></i>
        {% endif %}
            <i class="bi bi-speedometer2 me-2"></i> Summary 
        </a>
    </li>
    <hr id="horizontalLine">
    <li>
        <span class="text-uppercase small ps-2"><strong>Server</strong></span>
    </li>
    <li id="link-resources">
        {% if IS_USER_PRO %}
        <a href="{% url 'frontend:resources' %}" class="nav-link text-white {% if request.resolver_match.url_name == 'resources' %}active{% endif %}">
        {% else %}
        <a class="nav-link text-secondary disabled" style="pointer-events: none; opacity: 0.5;"> <i class="bi bi-lock" style="margin-right: 6px;"></i>
        {% endif %}
            <i class="bi bi-cpu me-2"></i> Resources 
        </a>
    </li>

        <li>
        {% if IS_USER_PRO %}
        <a href="{% url 'frontend:backup' %}" class="nav-link text-white {% if request.resolver_match.url_name == 'backup' %}active{% endif %}">
        {% else %}
        <a class="nav-link text-secondary disabled" style="pointer-events: none; opacity: 0.5;"> <i class="bi bi-lock" style="margin-right: 6px;"></i>
        {% endif %}
            <i class="bi bi-arrow-repeat"></i> Backup

        </a>
    </li>

<li>
    <div class="text-uppercase small ps-2" style="margin-top:15px;"><strong>Endpoint</strong></div>
</li>

    <li id="link-network">
        <a href="{% url 'frontend:network' %}" class="nav-link text-white {% if request.resolver_match.url_name == 'network' %}active{% endif %}">
            <i class="bi bi-diagram-3 me-2"></i> Network
        </a>
    </li>
    <li>
        <a href="{% url 'frontend:endpoints' %}" class="nav-link text-white {% if request.resolver_match.url_name == 'endpoints' %}active{% endif %}">
            <i class="bi bi-list-columns-reverse me-2"></i> Endpoints list
        </a>
    </li>

    {% comment %} <li>
        <span class="text-uppercase small ps-2"><strong>Backup</strong></span>
    </li> {% endcomment %}

    {% comment %} <li>
        {% if IS_USER_PRO %}
        <a href="{% url 'frontend:report' %}" class="nav-link text-white {% if request.resolver_match.url_name == 'report' %}active{% endif %}">
        {% else %}
        <a class="nav-link text-secondary disabled" style="pointer-events: none; opacity: 0.5;"> <i class="bi bi-lock" style="margin-right: 6px;"></i>
        {% endif %}
            <i class="bi bi-graph-up"></i> Report
        </a>
    </li> {% endcomment %}
</ul>


    <hr>
    <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            {% if request.user.profile_picture %}
                <img src="{{ request.user.profile_picture.url }}" alt="Foto profilo" width="32" height="32" class="rounded-circle me-2">
            {% else %}
                <img src="{% static 'frontend/images/user.png' %}" alt="Default" width="32" height="32" class="rounded-circle me-2">
            {% endif %}
            <strong>{{request.user}}</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
            {% if user.is_superuser %}
            <li><a class="dropdown-item" href="/admin/">Admin</a></li>
            {% endif %}
            <li><a class="dropdown-item" href="{% url 'users:edit_profile' %}">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li>
                <form method="post" action="{% url 'users:logout' %}">
                  {% csrf_token %}
                  <button type="submit" class="dropdown-item text-start w-100 text-danger">
                    <strong>Logout</strong>
                  </button>
                </form>
            </li>
        </ul>
    </div>
</div>

frontend/templates/frontend/components/status_dot.html
<span 
  style="display:inline-block; width:{{ dim }}; height:{{ dim }}; border-radius:50%; background:{{ color }}; margin-top: 5px;"
  title="{{ title|default:'' }}">
</span>